CATEGORY_DICT = { 0: 'Arts & Photography',
                 1: 'Biographies & Memoirs',
                 2: 'Business & Money',
                 3: 'Calendars',
                 4: "Children's Books",
                 5: 'Comics & Graphic Novels',
                 6: 'Computers & Technology',
                 7: 'Cookbooks, Food & Wine',
                 8: 'Crafts, Hobbies & Home',
                 9: 'Christian Books & Bibles',
                 10: 'Engineering & Transportation',
                 11: 'Health, Fitness & Dieting',
                 12: 'History',
                 13: 'Humor & Entertainment',
                 14: 'Law',
                 15: 'Literature & Fiction',
                 16: 'Medical Books',
                 17: 'Mystery, Thriller & Suspense',
                 18: 'Parenting & Relationships',
                 19: 'Politics & Social Sciences',
                 20: 'Reference',
                 21: 'Religion & Spirituality',
                 22: 'Romance',
                 23: 'Science & Math',
                 24: 'Science Fiction & Fantasy',
                 25: 'Self-Help',
                 26: 'Sports & Outdoors',
                 27: 'Teen & Young Adult',
                 28: 'Test Preparation',
                 29: 'Travel',}

CATEGORY_DICT_8 = {0: 'History & Religion',
                   1: 'Relationships & Children',
                   2: 'Academic - Science',
                   3: 'Lifestyle & Fitness',
                   5: 'Academic - Humanities',
                   6: 'Arts & Hobbies',
                   4: 'Literature & Entertainment',
                   7: 'Academic - Pure'}
